version: "3.9"
services:
  backend_service:
    build: ./backend
    ports:
      - "5100:5100"
    environment:
      - ./backend/.env
    depends_on:
      - tendanz_db
    
  # frontend_service:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - backend_service

  tendanz_db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tendanz_db
    ports:
      - "5432:5432"