FROM python:3.12-slim
RUN apt-get update && apt-get install -y libpq-dev gcc && apt-get clean
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5100
CMD ["python", "run.py"]